export const id = "crittercism"

export const data = {
  "name": "Crittercism",
  "slug": "crittercism",
  "createdAt": "2013-05-14T23:02:41Z",
  "note": "",
  "website": "http://crittercism.com",
  "description": "Crittercism is a performance monitoring solution for your mobile apps. Crittercism provides real-time monitoring of crashes, exceptions, network service calls, and other critical mobile workflows.",
  "level": 3,
  "categories": [
    "Error and Performance Monitoring"
  ],
  "popularity": 0.0025948752,
  "platforms": {
    "browser": false,
    "mobile": true,
    "server": false
  },
  "methods": {
    "alias": false,
    "group": false,
    "identify": false,
    "pageview": false,
    "track": false
  },
  "basicOptions": [
    "appId"
  ],
  "advancedOptions": [
    "includeVersionCode",
    "shouldCollectLogcat",
    "monitorWebView"
  ],
  "options": {
    "appId": {
      "default": "",
      "description": "You can find your App ID on the Crittercism [Settings page](https://app.crittercism.com/developers). It should be 24 characters long, and look something like this: `93ac1026a7928a581c000002`.",
      "label": "App ID",
      "type": "string",
      "validators": [
        [
          "required",
          "Please enter your Crittercism App ID."
        ],
        [
          "regexp",
          "^[a-z0-9]{24}$",
          "Please double check your App ID. It should be 24 characters long, and look something like this: `93ac1026a7928a581c000002`."
        ]
      ]
    },
    "customVersionName": {
      "default": "",
      "description": "Override the default version name of your app that is reported to Crittercism (Android only). Check out the [Crittercism docs](http://docs.crittercism.com/android/android.html#customizing-the-version-reported-to-crittercism) for more info.",
      "label": "Custom Version Name (Android)",
      "type": "String"
    },
    "enableServiceMonitoring": {
      "default": true,
      "description": "Whenever an app makes a network call, Crittercism monitors and captures certain information automatically (Android only). Check out the [Crittercism docs](http://docs.crittercism.com/overview/overview.html#service-monitoring) for more info.",
      "label": "Enable Service Monitoring (Android)",
      "type": "boolean"
    },
    "includeVersionCode": {
      "default": false,
      "description": "This will include the version code from the manifest file in your app's version name (Android only). Check out the [Crittercism docs](https://app.crittercism.com/developers/docs-optional-android#include_version_code) for more info.",
      "label": "Include the Version Code (Android)",
      "type": "boolean"
    },
    "monitorWebView": {
      "default": false,
      "description": "Monitor network traffic generated by UIWebViews (iOS only). Check out the [Crittercism docs](http://docs.crittercism.com/ios/ios.html#monitoring-web-views) for more info.",
      "label": "Monitor Web View (iOS)",
      "type": "boolean"
    },
    "shouldCollectLogcat": {
      "default": false,
      "description": "If you want to include system log data in your crash logs, enable this setting (Android only). Check out the [Crittercism docs](https://app.crittercism.com/developers/docs-optional-android#including_logcat) for more info.",
      "label": "Collect Logcat Data (Android)",
      "type": "boolean"
    }
  },
  "public": true,
  "redshift": false,
  "logos": {
    "default": "https://s3.amazonaws.com/segmentio/logos/crittercism-default.svg"
  },
  "id": "crittercism"
}

export const logos = {
  "default": "https://s3.amazonaws.com/segmentio/logos/crittercism-default.svg"
}

export default data
