#!/usr/bin/env node

require('skypager-cli/skypager-cli')

const cli = require('skypager-repl/dist/cli').default
const { colors, print, clear } = cli
const { red } = colors

process.on('unhandledRejection', (reason, promise) => {
  clear()
  print(red(`Unhandled Rejection`))
  print(red(reason), 2, 2, 2)
})
